from cgInTools.maya.library import cNurbs as ps; reload(ps);

locator_dicts=[
{"name":"hip01_surf_CF","locators":["legUp01_loc_R","legUp01_loc_L","legUp05_loc_L","legUp05_loc_R"]},
{"name":"hip01_surf_CB","locators":["legUp04_loc_L","legUp04_loc_R","legUp08_loc_R","legUp08_loc_L"]},
{"name":"hip01_surf_CD","locators":["legUp05_loc_R","legUp05_loc_L","legUp08_loc_L","legUp08_loc_R"]},
{"name":"hip02_surf_CF","locators":["spain04_loc_R","spain04_loc_L","legUp01_loc_L","legUp01_loc_R"]},
{"name":"hip02_surf_CB","locators":["spain01_loc_L","spain01_loc_R","legUp04_loc_R","legUp04_loc_L"]},
{"name":"spine_surf_CF","locators":["spain08_loc_R","spain08_loc_L","spain04_loc_L","spain04_loc_R"]},
{"name":"spine_surf_CB","locators":["spain05_loc_L","spain05_loc_R","spain01_loc_R","spain01_loc_L"]},
{"name":"chest_surf_CF","locators":["clavicle04_loc_R","clavicle04_loc_L","spain08_loc_L","spain08_loc_R"]},
{"name":"chest_surf_CB","locators":["clavicle03_loc_L","clavicle03_loc_R","spain05_loc_R","spain05_loc_L"]},
{"name":"neck_surf_CF","locators":["head02_loc_R","head02_loc_L","clavicle01_loc_L","clavicle01_loc_R"]},
{"name":"neck_surf_CB","locators":["head01_loc_L","head01_loc_R","clavicle02_loc_R","clavicle02_loc_L"]},
{"name":"head01_surf_CF","locators":["head06_loc_R","head06_loc_L","head03_loc_L","head03_loc_R"]},
{"name":"head01_surf_CB","locators":["head04_loc_L","head04_loc_R","head01_loc_R","head01_loc_L"]},
{"name":"head01_surf_CD","locators":["head03_loc_R","head03_loc_L","head02_loc_L","head02_loc_R"]},
{"name":"head02_surf_CF","locators":["head09_loc_R","head09_loc_L","head06_loc_L","head06_loc_R"]},
{"name":"head02_surf_CB","locators":["head07_loc_L","head07_loc_R","head04_loc_R","head04_loc_L"]},
{"name":"head02_surf_CUF","locators":["head08_loc_R","head08_loc_L","head09_loc_L","head09_loc_R"]},
{"name":"head02_surf_CUB","locators":["head07_loc_R","head07_loc_L","head08_loc_L","head08_loc_R"]},
{"name":"shoulder_surf_CF","locators":["clavicle01_loc_R","clavicle01_loc_L","clavicle04_loc_L","clavicle04_loc_R"]},
{"name":"shoulder_surf_CB","locators":["clavicle02_loc_L","clavicle02_loc_R","clavicle03_loc_R","clavicle03_loc_L"]},

{"name":"toe_surf_LI","locators":["toe04_loc_L","toe01_loc_L","toe05_loc_L","toe08_loc_L"]},
{"name":"toe_surf_LF","locators":["toe05_loc_L","toe06_loc_L","toe07_loc_L","toe08_loc_L"]},
{"name":"toe_surf_LO","locators":["toe02_loc_L","toe03_loc_L","toe07_loc_L","toe06_loc_L"]},
{"name":"toe_surf_LU","locators":["toe01_loc_L","toe02_loc_L","toe06_loc_L","toe05_loc_L"]},
{"name":"toe_surf_LD","locators":["toe03_loc_L","toe04_loc_L","toe08_loc_L","toe07_loc_L"]},
{"name":"foot_surf_LI","locators":["ankle05_loc_L","ankle01_loc_L","toe01_loc_L","toe04_loc_L"]},
{"name":"foot_surf_LU","locators":["ankle01_loc_L","ankle02_loc_L","toe02_loc_L","toe01_loc_L"]},
{"name":"foot_surf_LO","locators":["ankle02_loc_L","ankle06_loc_L","toe03_loc_L","toe02_loc_L"]},
{"name":"foot_surf_LD","locators":["ankle06_loc_L","ankle05_loc_L","toe04_loc_L","toe03_loc_L"]},
{"name":"heel_surf_LI","locators":["ankle04_loc_L","ankle01_loc_L","ankle05_loc_L","ankle08_loc_L"]},
{"name":"heel_surf_LD","locators":["ankle07_loc_L","ankle08_loc_L","ankle05_loc_L","ankle06_loc_L"]},
{"name":"heel_surf_LO","locators":["ankle02_loc_L","ankle03_loc_L","ankle07_loc_L","ankle06_loc_L"]},
{"name":"heel_surf_LB","locators":["ankle03_loc_L","ankle04_loc_L","ankle08_loc_L","ankle07_loc_L"]},
{"name":"ankle_surf_LI","locators":["legLow08_loc_L","legLow05_loc_L","ankle01_loc_L","ankle04_loc_L"]},
{"name":"ankle_surf_LF","locators":["legLow05_loc_L","legLow06_loc_L","ankle02_loc_L","ankle01_loc_L"]},
{"name":"ankle_surf_LO","locators":["legLow06_loc_L","legLow07_loc_L","ankle03_loc_L","ankle02_loc_L"]},
{"name":"ankle_surf_LB","locators":["legLow07_loc_L","legLow08_loc_L","ankle04_loc_L","ankle03_loc_L"]},
{"name":"legLow_surf_LI","locators":["legLow04_loc_L","legLow01_loc_L","legLow05_loc_L","legLow08_loc_L"]},
{"name":"legLow_surf_LF","locators":["legLow01_loc_L","legLow02_loc_L","legLow06_loc_L","legLow05_loc_L"]},
{"name":"legLow_surf_LO","locators":["legLow02_loc_L","legLow03_loc_L","legLow07_loc_L","legLow06_loc_L"]},
{"name":"legLow_surf_LB","locators":["legLow03_loc_L","legLow04_loc_L","legLow08_loc_L","legLow07_loc_L"]},
{"name":"knee_surf_LI","locators":["legUp12_loc_L","legUp09_loc_L","legLow01_loc_L","legLow04_loc_L"]},
{"name":"knee_surf_LF","locators":["knee01_loc_L","knee02_loc_L","knee03_loc_L","knee04_loc_L"]},
{"name":"knee_surf_LFI","locators":["legUp09_loc_L","knee01_loc_L","knee04_loc_L","legLow01_loc_L"]},
{"name":"knee_surf_LFU","locators":["legUp09_loc_L","legUp10_loc_L","knee02_loc_L","knee01_loc_L"]},
{"name":"knee_surf_LFO","locators":["knee02_loc_L","legUp10_loc_L","legLow02_loc_L","knee03_loc_L"]},
{"name":"knee_surf_LFD","locators":["knee04_loc_L","knee03_loc_L","legLow02_loc_L","legLow01_loc_L"]},
{"name":"knee_surf_LO","locators":["legUp10_loc_L","legUp11_loc_L","legLow03_loc_L","legLow02_loc_L"]},
{"name":"knee_surf_LB","locators":["legUp11_loc_L","legUp12_loc_L","legLow04_loc_L","legLow03_loc_L"]},
{"name":"legUp_surf_LI","locators":["legUp08_loc_L","legUp05_loc_L","legUp09_loc_L","legUp12_loc_L"]},
{"name":"legUp_surf_LF","locators":["legUp05_loc_L","legUp06_loc_L","legUp10_loc_L","legUp09_loc_L"]},
{"name":"legUp_surf_LO","locators":["legUp06_loc_L","legUp07_loc_L","legUp11_loc_L","legUp10_loc_L"]},
{"name":"legUp_surf_LB","locators":["legUp07_loc_L","legUp08_loc_L","legUp12_loc_L","legUp11_loc_L"]},
{"name":"hip01_surf_LF","locators":["legUp01_loc_L","legUp02_loc_L","legUp06_loc_L","legUp05_loc_L"]},
{"name":"hip01_surf_LO","locators":["legUp02_loc_L","legUp03_loc_L","legUp07_loc_L","legUp06_loc_L"]},
{"name":"hip01_surf_LB","locators":["hip01_loc_L","hip02_loc_L","hip03_loc_L","hip04_loc_L"]},
{"name":"hip01_surf_LBI","locators":["hip02_loc_L","legUp04_loc_L","legUp08_loc_L","hip03_loc_L"]},
{"name":"hip01_surf_LBU","locators":["legUp03_loc_L","legUp04_loc_L","hip02_loc_L","hip01_loc_L"]},
{"name":"hip01_surf_LBO","locators":["legUp03_loc_L","hip01_loc_L","hip04_loc_L","legUp07_loc_L"]},
{"name":"hip01_surf_LBD","locators":["hip04_loc_L","hip03_loc_L","legUp08_loc_L","legUp07_loc_L"]},
{"name":"hip02_surf_LF","locators":["spain04_loc_L","spain03_loc_L","legUp02_loc_L","legUp01_loc_L"]},
{"name":"hip02_surf_LO","locators":["spain03_loc_L","spain02_loc_L","legUp03_loc_L","legUp02_loc_L"]},
{"name":"hip02_surf_LB","locators":["spain02_loc_L","spain01_loc_L","legUp04_loc_L","legUp03_loc_L"]},
{"name":"spine_surf_LF","locators":["spain08_loc_L","spain07_loc_L","spain03_loc_L","spain04_loc_L"]},
{"name":"spine_surf_LO","locators":["spain07_loc_L","spain06_loc_L","spain02_loc_L","spain03_loc_L"]},
{"name":"spine_surf_LB","locators":["spain06_loc_L","spain05_loc_L","spain01_loc_L","spain02_loc_L"]},
{"name":"chest_surf_LF","locators":["clavicle04_loc_L","clavicle08_loc_L","spain07_loc_L","spain08_loc_L"]},
{"name":"chest_surf_LO","locators":["clavicle08_loc_L","clavicle07_loc_L","spain06_loc_L","spain07_loc_L"]},
{"name":"chest_surf_LB","locators":["clavicle07_loc_L","clavicle03_loc_L","spain05_loc_L","spain06_loc_L"]},
{"name":"neck_surf_LO","locators":["head02_loc_L","head01_loc_L","clavicle02_loc_L","clavicle01_loc_L"]},
{"name":"head01_surf_LOF","locators":["head06_loc_L","head05_loc_L","head02_loc_L","head03_loc_L"]},
{"name":"head01_surf_LOB","locators":["head05_loc_L","head04_loc_L","head01_loc_L","head02_loc_L"]},
{"name":"head02_surf_LOF","locators":["head09_loc_L","head08_loc_L","head05_loc_L","head06_loc_L"]},
{"name":"head02_surf_LOB","locators":["head08_loc_L","head07_loc_L","head04_loc_L","head05_loc_L"]},
{"name":"shoulder_surf_LF","locators":["clavicle01_loc_L","clavicle05_loc_L","clavicle08_loc_L","clavicle04_loc_L"]},
{"name":"shoulder_surf_LU","locators":["clavicle02_loc_L","locator06_loc_L","clavicle05_loc_L","clavicle01_loc_L"]},
{"name":"shoulder_surf_LB","locators":["locator06_loc_L","clavicle02_loc_L","clavicle03_loc_L","clavicle07_loc_L"]},
{"name":"shoulderRing_surf_LF","locators":["clavicle05_loc_L","clavicle09_loc_L","clavicle12_loc_L","clavicle08_loc_L"]},
{"name":"shoulderRing_surf_LU","locators":["locator06_loc_L","clavicle10_loc_L","clavicle09_loc_L","clavicle05_loc_L"]},
{"name":"shoulderRing_surf_LB","locators":["clavicle10_loc_L","locator06_loc_L","clavicle07_loc_L","clavicle11_loc_L"]},
{"name":"shoulderRing_surf_LD","locators":["clavicle08_loc_L","clavicle12_loc_L","clavicle11_loc_L","clavicle07_loc_L"]},
{"name":"shoulderArm_surf_LF","locators":["clavicle09_loc_L","armUp01_loc_L","armUp03_loc_L","clavicle12_loc_L"]},
{"name":"shoulderArm_surf_LO","locators":["armUp01_loc_L","armUp02_loc_L","armUp04_loc_L","armUp03_loc_L"]},
{"name":"shoulderArm_surf_LB","locators":["armUp02_loc_L","clavicle10_loc_L","clavicle11_loc_L","armUp04_loc_L"]},
{"name":"shoulderArm_surf_LU","locators":["clavicle09_loc_L","clavicle10_loc_L","armUp02_loc_L","armUp01_loc_L"]},
{"name":"armUp_surf_LI","locators":["clavicle11_loc_L","clavicle12_loc_L","armUp08_loc_L","armUp07_loc_L"]},
{"name":"armUp_surf_LF","locators":["clavicle12_loc_L","armUp03_loc_L","armUp05_loc_L","armUp08_loc_L"]},
{"name":"armUp_surf_LO","locators":["armUp03_loc_L","armUp04_loc_L","armUp06_loc_L","armUp05_loc_L"]},
{"name":"armUp_surf_LB","locators":["armUp04_loc_L","clavicle11_loc_L","armUp07_loc_L","armUp06_loc_L"]},
{"name":"elbow_surf_LI","locators":["armUp07_loc_L","armUp08_loc_L","armLow04_loc_L","armLow03_loc_L"]},
{"name":"elbow_surf_LF","locators":["armUp08_loc_L","armUp05_loc_L","armLow01_loc_L","armLow04_loc_L"]},
{"name":"elbow_surf_LO","locators":["armUp05_loc_L","armUp06_loc_L","armLow02_loc_L","armLow01_loc_L"]},
{"name":"elbow_surf_LB","locators":["elbow01_loc_L","elbow02_loc_L","elbow03_loc_L","elbow04_loc_L"]},
{"name":"elbow_surf_LBI","locators":["elbow02_loc_L","armUp07_loc_L","armLow03_loc_L","elbow03_loc_L"]},
{"name":"elbow_surf_LBU","locators":["armUp06_loc_L","armUp07_loc_L","elbow02_loc_L","elbow01_loc_L"]},
{"name":"elbow_surf_LBO","locators":["armUp06_loc_L","elbow01_loc_L","elbow04_loc_L","armLow02_loc_L"]},
{"name":"elbow_surf_LBD","locators":["elbow04_loc_L","elbow03_loc_L","armLow03_loc_L","armLow02_loc_L"]},
{"name":"armLow_surf_LI","locators":["armLow03_loc_L","armLow04_loc_L","armLow08_loc_L","armLow07_loc_L"]},
{"name":"armLow_surf_LF","locators":["armLow04_loc_L","armLow01_loc_L","armLow05_loc_L","armLow08_loc_L"]},
{"name":"armLow_surf_LO","locators":["armLow01_loc_L","armLow02_loc_L","armLow06_loc_L","armLow05_loc_L"]},
{"name":"armLow_surf_LB","locators":["armLow02_loc_L","armLow03_loc_L","armLow07_loc_L","armLow06_loc_L"]},
{"name":"wrist_surf_LI","locators":["armLow07_loc_L","armLow08_loc_L","hand04_loc_L","hand03_loc_L"]},
{"name":"wrist_surf_LF","locators":["armLow08_loc_L","armLow05_loc_L","hand01_loc_L","hand04_loc_L"]},
{"name":"wrist_surf_LO","locators":["armLow05_loc_L","armLow06_loc_L","hand02_loc_L","hand01_loc_L"]},
{"name":"wrist_surf_LB","locators":["armLow06_loc_L","armLow07_loc_L","hand03_loc_L","hand02_loc_L"]},
{"name":"hand01_surf_LI","locators":["hand03_loc_L","hand04_loc_L","hand08_loc_L","hand07_loc_L"]},
{"name":"hand01_surf_LO","locators":["hand01_loc_L","hand02_loc_L","hand06_loc_L","hand05_loc_L"]},
{"name":"hand01_surf_LB","locators":["hand02_loc_L","hand03_loc_L","hand07_loc_L","hand06_loc_L"]},
{"name":"hand02_surf_LI","locators":["hand07_loc_L","hand08_loc_L","hand12_loc_L","hand11_loc_L"]},
{"name":"hand02_surf_LF","locators":["hand08_loc_L","hand05_loc_L","hand09_loc_L","hand12_loc_L"]},
{"name":"hand02_surf_LO","locators":["hand05_loc_L","hand06_loc_L","hand10_loc_L","hand09_loc_L"]},
{"name":"hand02_surf_LB","locators":["hand06_loc_L","hand07_loc_L","hand11_loc_L","hand10_loc_L"]},
{"name":"hand03_surf_LI","locators":["hand11_loc_L","hand12_loc_L","hand16_loc_L","hand15_loc_L"]},
{"name":"hand03_surf_LF","locators":["hand12_loc_L","hand09_loc_L","hand13_loc_L","hand16_loc_L"]},
{"name":"hand03_surf_LO","locators":["hand09_loc_L","hand10_loc_L","hand14_loc_L","hand13_loc_L"]},
{"name":"hand03_surf_LB","locators":["hand10_loc_L","hand11_loc_L","hand15_loc_L","hand14_loc_L"]},
{"name":"hand03_surf_LD","locators":["hand13_loc_L","hand14_loc_L","hand15_loc_L","hand16_loc_L"]},
{"name":"hand04_surf_LI","locators":["hand04_loc_L","hand18_loc_L","hand20_loc_L","hand08_loc_L"]},
{"name":"hand04_surf_LF","locators":["hand18_loc_L","hand17_loc_L","hand19_loc_L","hand20_loc_L"]},
{"name":"hand04_surf_LO","locators":["hand17_loc_L","hand01_loc_L","hand05_loc_L","hand19_loc_L"]},
{"name":"hand04_surf_LU","locators":["hand04_loc_L","hand01_loc_L","hand17_loc_L","hand18_loc_L"]},
{"name":"hand05_surf_LI","locators":["hand08_loc_L","hand20_loc_L","hand24_loc_L","hand23_loc_L"]},
{"name":"hand05_surf_LF","locators":["hand20_loc_L","hand19_loc_L","hand21_loc_L","hand24_loc_L"]},
{"name":"hand05_surf_LO","locators":["hand19_loc_L","hand05_loc_L","hand22_loc_L","hand21_loc_L"]},
{"name":"hand05_surf_LB","locators":["hand05_loc_L","hand08_loc_L","hand23_loc_L","hand22_loc_L"]},
{"name":"hand05_surf_LD","locators":["hand21_loc_L","hand22_loc_L","hand23_loc_L","hand24_loc_L"]},

{"name":"toe_surf_RI","locators":["toe05_loc_R","toe01_loc_R","toe04_loc_R","toe08_loc_R"]},
{"name":"toe_surf_RF","locators":["toe06_loc_R","toe05_loc_R","toe08_loc_R","toe07_loc_R"]},

{"name":"toe_surf_RO","locators":[u'toe02_loc_R', u'toe06_loc_R', u'toe07_loc_R', u'toe03_loc_R']},
{"name":"toe_surf_RU","locators":[u'toe02_loc_R', u'toe01_loc_R', u'toe05_loc_R', u'toe06_loc_R']},
{"name":"toe_surf_RD","locators":[u'toe04_loc_R', u'toe03_loc_R', u'toe07_loc_R', u'toe08_loc_R']},
{"name":"foot_surf_RI","locators":[u'toe01_loc_R', u'ankle01_loc_R', u'ankle05_loc_R', u'toe04_loc_R']},
{"name":"foot_surf_RU","locators":[u'ankle02_loc_R', u'ankle01_loc_R', u'toe01_loc_R', u'toe02_loc_R']},
{"name":"foot_surf_RO","locators":[u'ankle02_loc_R', u'toe02_loc_R', u'toe03_loc_R', u'ankle06_loc_R']},
{"name":"foot_surf_RD","locators":[u'ankle05_loc_R', u'ankle06_loc_R', u'toe03_loc_R', u'toe04_loc_R']},
{"name":"heel_surf_RI","locators":[u'ankle01_loc_R', u'ankle04_loc_R', u'ankle08_loc_R', u'ankle05_loc_R']},
{"name":"heel_surf_RD","locators":[u'ankle06_loc_R', u'ankle05_loc_R', u'ankle08_loc_R', u'ankle07_loc_R']},
{"name":"heel_surf_RO","locators":[u'ankle03_loc_R', u'ankle02_loc_R', u'ankle06_loc_R', u'ankle07_loc_R']},
{"name":"heel_surf_RB","locators":[u'ankle04_loc_R', u'ankle03_loc_R', u'ankle07_loc_R', u'ankle08_loc_R']},
{"name":"ankle_surf_RI","locators":[u'legLow05_loc_R', u'legLow08_loc_R', u'ankle04_loc_R', u'ankle01_loc_R']},
{"name":"ankle_surf_RF","locators":[u'legLow06_loc_R', u'legLow05_loc_R', u'ankle01_loc_R', u'ankle02_loc_R']},
{"name":"ankle_surf_RO","locators":[u'legLow07_loc_R', u'legLow06_loc_R', u'ankle02_loc_R', u'ankle03_loc_R']},
{"name":"ankle_surf_RB","locators":[u'legLow08_loc_R', u'legLow07_loc_R', u'ankle03_loc_R', u'ankle04_loc_R']},
{"name":"legLow_surf_RI","locators":[u'legLow01_loc_R', u'legLow04_loc_R', u'legLow08_loc_R', u'legLow05_loc_R']},
{"name":"legLow_surf_RF","locators":[u'legLow02_loc_R', u'legLow01_loc_R', u'legLow05_loc_R', u'legLow06_loc_R']},
{"name":"legLow_surf_RO","locators":[u'legLow03_loc_R', u'legLow02_loc_R', u'legLow06_loc_R', u'legLow07_loc_R']},
{"name":"legLow_surf_RB","locators":[u'legLow04_loc_R', u'legLow03_loc_R', u'legLow07_loc_R', u'legLow08_loc_R']},

{"name":"knee_surf_RI","locators":[u'legUp09_loc_R', u'legUp12_loc_R', u'legLow04_loc_R', u'legLow01_loc_R']},
{"name":"knee_surf_RF","locators":[u'knee02_loc_R', u'knee01_loc_R', u'knee04_loc_R', u'knee03_loc_R']},
{"name":"knee_surf_RFI","locators":[u'knee01_loc_R', u'legUp09_loc_R', u'legLow01_loc_R', u'knee04_loc_R']},
{"name":"knee_surf_RFU","locators":[u'legUp10_loc_R', u'legUp09_loc_R', u'knee01_loc_R', u'knee02_loc_R']},
{"name":"knee_surf_RFO","locators":[u'legUp10_loc_R', u'knee02_loc_R', u'knee03_loc_R', u'legLow02_loc_R']},
{"name":"knee_surf_RFD","locators":[u'knee03_loc_R', u'knee04_loc_R', u'legLow01_loc_R', u'legLow02_loc_R']},
{"name":"knee_surf_RO","locators":[u'legUp11_loc_R', u'legUp10_loc_R', u'legLow02_loc_R', u'legLow03_loc_R']},
{"name":"knee_surf_RB","locators":[u'legUp12_loc_R', u'legUp11_loc_R', u'legLow03_loc_R', u'legLow04_loc_R']},
{"name":"legUp_surf_RI","locators":["legUp08_loc_R","legUp05_loc_R","legUp09_loc_R","legUp12_loc_R"]},
{"name":"legUp_surf_RF","locators":["legUp05_loc_R","legUp06_loc_R","legUp10_loc_R","legUp09_loc_R"]},
{"name":"legUp_surf_RO","locators":["legUp06_loc_R","legUp07_loc_R","legUp11_loc_R","legUp10_loc_R"]},
{"name":"legUp_surf_RB","locators":["legUp07_loc_R","legUp08_loc_R","legUp12_loc_R","legUp11_loc_R"]},
{"name":"hip01_surf_RF","locators":["legUp01_loc_R","legUp02_loc_R","legUp06_loc_R","legUp05_loc_R"]},
{"name":"hip01_surf_RO","locators":["legUp02_loc_R","legUp03_loc_R","legUp07_loc_R","legUp06_loc_R"]},
{"name":"hip01_surf_RB","locators":["hip01_loc_R","hip02_loc_R","hip03_loc_R","hip04_loc_R"]},
{"name":"hip01_surf_RBI","locators":["hip02_loc_R","legUp04_loc_R","legUp08_loc_R","hip03_loc_R"]},
{"name":"hip01_surf_RBU","locators":["legUp03_loc_R","legUp04_loc_R","hip02_loc_R","hip01_loc_R"]},
{"name":"hip01_surf_RBO","locators":["legUp03_loc_R","hip01_loc_R","hip04_loc_R","legUp07_loc_R"]},
{"name":"hip01_surf_RBD","locators":["hip04_loc_R","hip03_loc_R","legUp08_loc_R","legUp07_loc_R"]},
{"name":"hip02_surf_RF","locators":["spain04_loc_R","spain03_loc_R","legUp02_loc_R","legUp01_loc_R"]},
{"name":"hip02_surf_RO","locators":["spain03_loc_R","spain02_loc_R","legUp03_loc_R","legUp02_loc_R"]},
{"name":"hip02_surf_RB","locators":["spain02_loc_R","spain01_loc_R","legUp04_loc_R","legUp03_loc_R"]},
{"name":"spine_surf_RF","locators":["spain08_loc_R","spain07_loc_R","spain03_loc_R","spain04_loc_R"]},
{"name":"spine_surf_RO","locators":["spain07_loc_R","spain06_loc_R","spain02_loc_R","spain03_loc_R"]},
{"name":"spine_surf_RB","locators":["spain06_loc_R","spain05_loc_R","spain01_loc_R","spain02_loc_R"]},
{"name":"chest_surf_RF","locators":["clavicle04_loc_R","clavicle08_loc_R","spain07_loc_R","spain08_loc_R"]},
{"name":"chest_surf_RO","locators":["clavicle08_loc_R","clavicle07_loc_R","spain06_loc_R","spain07_loc_R"]},
{"name":"chest_surf_RB","locators":["clavicle07_loc_R","clavicle03_loc_R","spain05_loc_R","spain06_loc_R"]},
{"name":"neck_surf_RO","locators":["head02_loc_R","head01_loc_R","clavicle02_loc_R","clavicle01_loc_R"]},
{"name":"head01_surf_ROF","locators":["head06_loc_R","head05_loc_R","head02_loc_R","head03_loc_R"]},
{"name":"head01_surf_ROB","locators":["head05_loc_R","head04_loc_R","head01_loc_R","head02_loc_R"]},
{"name":"head02_surf_ROF","locators":["head09_loc_R","head08_loc_R","head05_loc_R","head06_loc_R"]},
{"name":"head02_surf_ROB","locators":["head08_loc_R","head07_loc_R","head04_loc_R","head05_loc_R"]},
{"name":"shoulder_surf_RF","locators":["clavicle01_loc_R","clavicle05_loc_R","clavicle08_loc_R","clavicle04_loc_R"]},
{"name":"shoulder_surf_RU","locators":["clavicle02_loc_R","locator06_loc_R","clavicle05_loc_R","clavicle01_loc_R"]},
{"name":"shoulder_surf_RB","locators":["locator06_loc_R","clavicle02_loc_R","clavicle03_loc_R","clavicle07_loc_R"]},
{"name":"shoulderRing_surf_RF","locators":["clavicle05_loc_R","clavicle09_loc_R","clavicle12_loc_R","clavicle08_loc_R"]},
{"name":"shoulderRing_surf_RU","locators":["locator06_loc_R","clavicle10_loc_R","clavicle09_loc_R","clavicle05_loc_R"]},
{"name":"shoulderRing_surf_RB","locators":["clavicle10_loc_R","locator06_loc_R","clavicle07_loc_R","clavicle11_loc_R"]},
{"name":"shoulderRing_surf_RD","locators":["clavicle08_loc_R","clavicle12_loc_R","clavicle11_loc_R","clavicle07_loc_R"]},
{"name":"shoulderArm_surf_RF","locators":["clavicle09_loc_R","armUp01_loc_R","armUp03_loc_R","clavicle12_loc_R"]},
{"name":"shoulderArm_surf_RO","locators":["armUp01_loc_R","armUp02_loc_R","armUp04_loc_R","armUp03_loc_R"]},
{"name":"shoulderArm_surf_RB","locators":["armUp02_loc_R","clavicle10_loc_R","clavicle11_loc_R","armUp04_loc_R"]},
{"name":"shoulderArm_surf_RU","locators":["clavicle09_loc_R","clavicle10_loc_R","armUp02_loc_R","armUp01_loc_R"]},
{"name":"armUp_surf_RI","locators":["clavicle11_loc_R","clavicle12_loc_R","armUp08_loc_R","armUp07_loc_R"]},
{"name":"armUp_surf_RF","locators":["clavicle12_loc_R","armUp03_loc_R","armUp05_loc_R","armUp08_loc_R"]},
{"name":"armUp_surf_RO","locators":["armUp03_loc_R","armUp04_loc_R","armUp06_loc_R","armUp05_loc_R"]},
{"name":"armUp_surf_RB","locators":["armUp04_loc_R","clavicle11_loc_R","armUp07_loc_R","armUp06_loc_R"]},
{"name":"elbow_surf_RI","locators":["armUp07_loc_R","armUp08_loc_R","armLow04_loc_R","armLow03_loc_R"]},
{"name":"elbow_surf_RF","locators":["armUp08_loc_R","armUp05_loc_R","armLow01_loc_R","armLow04_loc_R"]},
{"name":"elbow_surf_RO","locators":["armUp05_loc_R","armUp06_loc_R","armLow02_loc_R","armLow01_loc_R"]},
{"name":"elbow_surf_RB","locators":["elbow01_loc_R","elbow02_loc_R","elbow03_loc_R","elbow04_loc_R"]},
{"name":"elbow_surf_RBI","locators":["elbow02_loc_R","armUp07_loc_R","armLow03_loc_R","elbow03_loc_R"]},
{"name":"elbow_surf_RBU","locators":["armUp06_loc_R","armUp07_loc_R","elbow02_loc_R","elbow01_loc_R"]},
{"name":"elbow_surf_RBO","locators":["armUp06_loc_R","elbow01_loc_R","elbow04_loc_R","armLow02_loc_R"]},
{"name":"elbow_surf_RBD","locators":["elbow04_loc_R","elbow03_loc_R","armLow03_loc_R","armLow02_loc_R"]},
{"name":"armLow_surf_RI","locators":["armLow03_loc_R","armLow04_loc_R","armLow08_loc_R","armLow07_loc_R"]},
{"name":"armLow_surf_RF","locators":["armLow04_loc_R","armLow01_loc_R","armLow05_loc_R","armLow08_loc_R"]},
{"name":"armLow_surf_RO","locators":["armLow01_loc_R","armLow02_loc_R","armLow06_loc_R","armLow05_loc_R"]},
{"name":"armLow_surf_RB","locators":["armLow02_loc_R","armLow03_loc_R","armLow07_loc_R","armLow06_loc_R"]},
{"name":"wrist_surf_RI","locators":["armLow07_loc_R","armLow08_loc_R","hand04_loc_R","hand03_loc_R"]},
{"name":"wrist_surf_RF","locators":["armLow08_loc_R","armLow05_loc_R","hand01_loc_R","hand04_loc_R"]},
{"name":"wrist_surf_RO","locators":["armLow05_loc_R","armLow06_loc_R","hand02_loc_R","hand01_loc_R"]},
{"name":"wrist_surf_RB","locators":["armLow06_loc_R","armLow07_loc_R","hand03_loc_R","hand02_loc_R"]},
{"name":"hand01_surf_RI","locators":["hand03_loc_R","hand04_loc_R","hand08_loc_R","hand07_loc_R"]},
{"name":"hand01_surf_RO","locators":["hand01_loc_R","hand02_loc_R","hand06_loc_R","hand05_loc_R"]},
{"name":"hand01_surf_RB","locators":["hand02_loc_R","hand03_loc_R","hand07_loc_R","hand06_loc_R"]},
{"name":"hand02_surf_RI","locators":["hand07_loc_R","hand08_loc_R","hand12_loc_R","hand11_loc_R"]},
{"name":"hand02_surf_RF","locators":["hand08_loc_R","hand05_loc_R","hand09_loc_R","hand12_loc_R"]},
{"name":"hand02_surf_RO","locators":["hand05_loc_R","hand06_loc_R","hand10_loc_R","hand09_loc_R"]},
{"name":"hand02_surf_RB","locators":["hand06_loc_R","hand07_loc_R","hand11_loc_R","hand10_loc_R"]},
{"name":"hand03_surf_RI","locators":["hand11_loc_R","hand12_loc_R","hand16_loc_R","hand15_loc_R"]},
{"name":"hand03_surf_RF","locators":["hand12_loc_R","hand09_loc_R","hand13_loc_R","hand16_loc_R"]},
{"name":"hand03_surf_RO","locators":["hand09_loc_R","hand10_loc_R","hand14_loc_R","hand13_loc_R"]},
{"name":"hand03_surf_RB","locators":["hand10_loc_R","hand11_loc_R","hand15_loc_R","hand14_loc_R"]},
{"name":"hand03_surf_RD","locators":["hand13_loc_R","hand14_loc_R","hand15_loc_R","hand16_loc_R"]},
{"name":"hand04_surf_RI","locators":["hand04_loc_R","hand18_loc_R","hand20_loc_R","hand08_loc_R"]},
{"name":"hand04_surf_RF","locators":["hand18_loc_R","hand17_loc_R","hand19_loc_R","hand20_loc_R"]},
{"name":"hand04_surf_RO","locators":["hand17_loc_R","hand01_loc_R","hand05_loc_R","hand19_loc_R"]},
{"name":"hand04_surf_RU","locators":["hand04_loc_R","hand01_loc_R","hand17_loc_R","hand18_loc_R"]},
{"name":"hand05_surf_RI","locators":["hand08_loc_R","hand20_loc_R","hand24_loc_R","hand23_loc_R"]},
{"name":"hand05_surf_RF","locators":["hand20_loc_R","hand19_loc_R","hand21_loc_R","hand24_loc_R"]},
{"name":"hand05_surf_RO","locators":["hand19_loc_R","hand05_loc_R","hand22_loc_R","hand21_loc_R"]},
{"name":"hand05_surf_RB","locators":["hand05_loc_R","hand08_loc_R","hand23_loc_R","hand22_loc_R"]},
{"name":"hand05_surf_RD","locators":["hand21_loc_R","hand22_loc_R","hand23_loc_R","hand24_loc_R"]},
]

surf=ps.QuadPosSurface()
for locator in locator_dicts:
    surf.setName(locator["name"])
    surf.setLoctorsFour(locator["locators"])
    surf.create()