shirt={
    "root":[
        {
            "skc":"shirt_sskc_C",
            "params":[
                #spine_C0_0_jnt
                {
                    "vertex":[
                        "shirt_cage_C.vtx[0:437]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_0_jnt","value":1.0}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[0]",
                        "shirt_cage_C.vtx[3:4]",
                        "shirt_cage_C.vtx[7:8]",
                        "shirt_cage_C.vtx[11:12]",
                        "shirt_cage_C.vtx[14]",
                        "shirt_cage_C.vtx[17]",
                        "shirt_cage_C.vtx[19:20]",
                        "shirt_cage_C.vtx[23:24]",
                        "shirt_cage_C.vtx[27]",
                        "shirt_cage_C.vtx[29]",
                        "shirt_cage_C.vtx[31:437]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_1_jnt","value":1.0}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[0]",
                        "shirt_cage_C.vtx[3:4]",
                        "shirt_cage_C.vtx[7:8]",
                        "shirt_cage_C.vtx[11:12]",
                        "shirt_cage_C.vtx[14]",
                        "shirt_cage_C.vtx[17]",
                        "shirt_cage_C.vtx[19:20]",
                        "shirt_cage_C.vtx[23:24]",
                        "shirt_cage_C.vtx[27]",
                        "shirt_cage_C.vtx[29]",
                        "shirt_cage_C.vtx[31]",
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_0_jnt","value":0.75}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[233:248]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_0_jnt","value":0.447}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[32:47]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_0_jnt","value":0.170}
                    ],
                    "lockInfluence":"spine_C0_0_jnt"
                },
                #spine_C0_1_jnt
                {
                    "vertex":[
                        "shirt_cage_C.vtx[32:232]",
                        "shirt_cage_C.vtx[249:437]",
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_2_jnt","value":1.0}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[32:47]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_1_jnt","value":0.5}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[217:232]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_1_jnt","value":0.447}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[48:63]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_1_jnt","value":0.170}
                    ],
                    "lockInfluence":"spine_C0_1_jnt"
                },
                #spine_C0_2_jnt
                {
                    "vertex":[
                        "shirt_cage_C.vtx[48:216]",
                        "shirt_cage_C.vtx[249:437]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_3_jnt","value":1.0}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[48:63]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_2_jnt","value":0.5}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[201:216]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_2_jnt","value":0.46}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[64:79]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_2_jnt","value":0.170}
                    ],
                    "lockInfluence":"spine_C0_2_jnt"
                },
                #spine_C0_3_jnt
                {
                    "vertex":[
                        "shirt_cage_C.vtx[64:71]",
                        "shirt_cage_C.vtx[73:200]",
                        "shirt_cage_C.vtx[249:437]",
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_4_jnt","value":1.0}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[64:79]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_3_jnt","value":0.5}
                    ],
                    "lockInfluence":"spine_C0_3_jnt"
                },
                #spine_C0_4_jnt
                {
                    "vertex":[
                        "shirt_cage_C.vtx[64]",
                        "shirt_cage_C.vtx[67]",
                        "shirt_cage_C.vtx[69]",
                        "shirt_cage_C.vtx[71]",
                        "shirt_cage_C.vtx[73:74]",
                        "shirt_cage_C.vtx[77]",
                        "shirt_cage_C.vtx[80:81]",
                        "shirt_cage_C.vtx[84]",
                        "shirt_cage_C.vtx[86:87]",
                        "shirt_cage_C.vtx[90:91]",
                        "shirt_cage_C.vtx[94:95]",
                        "shirt_cage_C.vtx[98]",
                        "shirt_cage_C.vtx[100]",
                        "shirt_cage_C.vtx[103]",
                        "shirt_cage_C.vtx[106]",
                        "shirt_cage_C.vtx[108:109]",
                        "shirt_cage_C.vtx[112:113]",
                        "shirt_cage_C.vtx[116:117]",
                        "shirt_cage_C.vtx[120:121]",
                        "shirt_cage_C.vtx[124]",
                        "shirt_cage_C.vtx[127]",
                        "shirt_cage_C.vtx[131]",
                        "shirt_cage_C.vtx[133]",
                        "shirt_cage_C.vtx[135]",
                        "shirt_cage_C.vtx[137]",
                        "shirt_cage_C.vtx[139:140]",
                        "shirt_cage_C.vtx[143:144]",
                        "shirt_cage_C.vtx[147:150]",
                        "shirt_cage_C.vtx[155:156]",
                        "shirt_cage_C.vtx[159:160]",
                        "shirt_cage_C.vtx[163:164]",
                        "shirt_cage_C.vtx[167]",
                        "shirt_cage_C.vtx[169]",
                        "shirt_cage_C.vtx[171]",
                        "shirt_cage_C.vtx[173]",
                        "shirt_cage_C.vtx[175]",
                        "shirt_cage_C.vtx[177]",
                        "shirt_cage_C.vtx[179]",
                        "shirt_cage_C.vtx[181]",
                        "shirt_cage_C.vtx[183]",
                        "shirt_cage_C.vtx[185]",
                        "shirt_cage_C.vtx[187]",
                        "shirt_cage_C.vtx[189]",
                        "shirt_cage_C.vtx[191]",
                        "shirt_cage_C.vtx[193]",
                        "shirt_cage_C.vtx[249:250]",
                        "shirt_cage_C.vtx[253]",
                        "shirt_cage_C.vtx[255]",
                        "shirt_cage_C.vtx[257]",
                        "shirt_cage_C.vtx[260:261]",
                        "shirt_cage_C.vtx[263]",
                        "shirt_cage_C.vtx[265]",
                        "shirt_cage_C.vtx[267]",
                        "shirt_cage_C.vtx[269]",
                        "shirt_cage_C.vtx[271:272]",
                        "shirt_cage_C.vtx[275]",
                        "shirt_cage_C.vtx[277]",
                        "shirt_cage_C.vtx[279]",
                        "shirt_cage_C.vtx[281:282]",
                        "shirt_cage_C.vtx[285]",
                        "shirt_cage_C.vtx[287]",
                        "shirt_cage_C.vtx[289]",
                        "shirt_cage_C.vtx[292:293]",
                        "shirt_cage_C.vtx[295]",
                        "shirt_cage_C.vtx[297]",
                        "shirt_cage_C.vtx[299]",
                        "shirt_cage_C.vtx[301]",
                        "shirt_cage_C.vtx[303:304]",
                        "shirt_cage_C.vtx[307]",
                        "shirt_cage_C.vtx[309]",
                        "shirt_cage_C.vtx[311]",
                        "shirt_cage_C.vtx[313:322]",
                        "shirt_cage_C.vtx[333:342]",
                        "shirt_cage_C.vtx[362:371]",
                        "shirt_cage_C.vtx[374]",
                        "shirt_cage_C.vtx[376]",
                        "shirt_cage_C.vtx[378]",
                        "shirt_cage_C.vtx[381:382]",
                        "shirt_cage_C.vtx[384]",
                        "shirt_cage_C.vtx[387:388]",
                        "shirt_cage_C.vtx[390]",
                        "shirt_cage_C.vtx[392]",
                        "shirt_cage_C.vtx[394:395]",
                        "shirt_cage_C.vtx[398]",
                        "shirt_cage_C.vtx[400]",
                        "shirt_cage_C.vtx[402]",
                        "shirt_cage_C.vtx[404:405]",
                        "shirt_cage_C.vtx[408]",
                        "shirt_cage_C.vtx[410]",
                        "shirt_cage_C.vtx[412]",
                        "shirt_cage_C.vtx[415:416]",
                        "shirt_cage_C.vtx[418]",
                        "shirt_cage_C.vtx[421:422]",
                        "shirt_cage_C.vtx[424]",
                        "shirt_cage_C.vtx[426]",
                        "shirt_cage_C.vtx[428:429]",
                        "shirt_cage_C.vtx[432]",
                        "shirt_cage_C.vtx[434]",
                        "shirt_cage_C.vtx[436]",
                    ],
                    "transformValue":[
                        {"joint":"shoulder_L0_0_jnt","value":1.0}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[64]",
                        "shirt_cage_C.vtx[77]",
                        "shirt_cage_C.vtx[100]",
                        "shirt_cage_C.vtx[103]",
                        "shirt_cage_C.vtx[127]",
                        "shirt_cage_C.vtx[131]",
                        "shirt_cage_C.vtx[185]",
                        "shirt_cage_C.vtx[187]",
                        "shirt_cage_C.vtx[189]",
                        "shirt_cage_C.vtx[191]",
                        "shirt_cage_C.vtx[193]",
                        "shirt_cage_C.vtx[201]",
                        "shirt_cage_C.vtx[362]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_4_jnt","value":0.9}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[202:206]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_4_jnt","value":0.75}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[124]",
                        "shirt_cage_C.vtx[179]",
                        "shirt_cage_C.vtx[181]",
                        "shirt_cage_C.vtx[183]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_4_jnt","value":0.8}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[98]",
                        "shirt_cage_C.vtx[106]",
                        "shirt_cage_C.vtx[133]",
                        "shirt_cage_C.vtx[135]",
                        "shirt_cage_C.vtx[137]",
                        "shirt_cage_C.vtx[139:140]",
                        "shirt_cage_C.vtx[167]",
                        "shirt_cage_C.vtx[169]",
                        "shirt_cage_C.vtx[171]",
                        "shirt_cage_C.vtx[173]",
                        "shirt_cage_C.vtx[175]",
                        "shirt_cage_C.vtx[177]",
                        "shirt_cage_C.vtx[363]",
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_4_jnt","value":0.2}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[87]",
                        "shirt_cage_C.vtx[91]",
                        "shirt_cage_C.vtx[95]",
                        "shirt_cage_C.vtx[109]",
                        "shirt_cage_C.vtx[113]",
                        "shirt_cage_C.vtx[117]",
                        "shirt_cage_C.vtx[121]",
                        "shirt_cage_C.vtx[143]",
                        "shirt_cage_C.vtx[147]",
                        "shirt_cage_C.vtx[150]",
                        "shirt_cage_C.vtx[156]",
                        "shirt_cage_C.vtx[160]",
                        "shirt_cage_C.vtx[164]",
                        "shirt_cage_C.vtx[364]",
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_4_jnt","value":0.1}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[80:81]",
                        "shirt_cage_C.vtx[84]",
                        "shirt_cage_C.vtx[86]",
                        "shirt_cage_C.vtx[90]",
                        "shirt_cage_C.vtx[94]",
                        "shirt_cage_C.vtx[108]",
                        "shirt_cage_C.vtx[112]",
                        "shirt_cage_C.vtx[116]",
                        "shirt_cage_C.vtx[120]",
                        "shirt_cage_C.vtx[144]",
                        "shirt_cage_C.vtx[148:149]",
                        "shirt_cage_C.vtx[155]",
                        "shirt_cage_C.vtx[159]",
                        "shirt_cage_C.vtx[163]",
                        "shirt_cage_C.vtx[365]",
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_4_jnt","value":0.05}
                    ],
                    "lockInfluence":0
                },
            ]
        }
    ]
}

head={
    "root":[
        {
            "skc":"head_sskc_C",
            "params":[
                #spine_C0_4_jnt
                {
                    "vertex":[
                        "head_cage_C.vtx[0:669]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_4_jnt","value":1.0}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "head_cage_C.vtx[0:1]",
                        "head_cage_C.vtx[5]",
                        "head_cage_C.vtx[11:12]",
                        "head_cage_C.vtx[15:16]",
                        "head_cage_C.vtx[23]",
                        "head_cage_C.vtx[29]",
                        "head_cage_C.vtx[32]",
                        "head_cage_C.vtx[36]",
                        "head_cage_C.vtx[38]",
                        "head_cage_C.vtx[40]",
                        "head_cage_C.vtx[42]",
                        "head_cage_C.vtx[44]",
                        "head_cage_C.vtx[46:59]",
                        "head_cage_C.vtx[76:669]"
                    ],
                    "transformValue":[
                        {"joint":"neck_C0_0_jnt","value":1.0}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "head_cage_C.vtx[0:1]",
                        "head_cage_C.vtx[5]",
                        "head_cage_C.vtx[11:12]",
                        "head_cage_C.vtx[15:16]",
                        "head_cage_C.vtx[23]",
                        "head_cage_C.vtx[29]",
                        "head_cage_C.vtx[32]",
                        "head_cage_C.vtx[36]",
                        "head_cage_C.vtx[38]",
                        "head_cage_C.vtx[40]",
                        "head_cage_C.vtx[42]",
                        "head_cage_C.vtx[44]",
                        "head_cage_C.vtx[46]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_4_jnt","value":0.875}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "head_cage_C.vtx[79:94]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_4_jnt","value":0.53}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "head_cage_C.vtx[47:59]",
                        "head_cage_C.vtx[76:78]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_4_jnt","value":0.25}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "head_cage_C.vtx[95:110]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_4_jnt","value":0.15}
                    ],
                    "lockInfluence":"spine_C0_4_jnt"
                },
                #neck_C0_0_jnt
                {
                    "vertex":[
                        "head_cage_C.vtx[95:669]"
                    ],
                    "transformValue":[
                        {"joint":"neck_C0_1_jnt","value":1.0}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "head_cage_C.vtx[95:110]"
                    ],
                    "transformValue":[
                        {"joint":"neck_C0_0_jnt","value":0.5}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "head_cage_C.vtx[127:142]"
                    ],
                    "transformValue":[
                        {"joint":"neck_C0_0_jnt","value":0.25}
                    ],
                    "lockInfluence":"neck_C0_0_jnt"
                },
            ]
        }
    ]
}

arms={
    "root":[
        {
            "skc":"body_sskc_C",
            "params":[
                #spine_C0_0_jnt
                {
                    "vertex":[
                        "shirt_cage_C.vtx[0:437]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_0_jnt","value":1.0}
                    ],
                    "lockInfluence":0
                },
                {
                    "vertex":[
                        "shirt_cage_C.vtx[0]",
                        "shirt_cage_C.vtx[3:4]",
                        "shirt_cage_C.vtx[7:8]",
                        "shirt_cage_C.vtx[11:12]",
                        "shirt_cage_C.vtx[14]",
                        "shirt_cage_C.vtx[17]",
                        "shirt_cage_C.vtx[19:20]",
                        "shirt_cage_C.vtx[23:24]",
                        "shirt_cage_C.vtx[27]",
                        "shirt_cage_C.vtx[29]",
                        "shirt_cage_C.vtx[31:437]"
                    ],
                    "transformValue":[
                        {"joint":"spine_C0_1_jnt","value":1.0}
                    ],
                    "lockInfluence":0
                },
            ]
        }
    ]
}

import maya.cmds as cmds

#cmds.skinPercent("pants_sskc_C",tv=[("spine02_jnt_C",0.5),()])
#cmds.setAttr(transValue+".lockInfluenceWeights",0)

def lockInfluenceSwitch_check_func(jointObj_str=0):
    if jointObj_str==0:
        pass
    elif cmds.nodeType(jointObj_str)=="joint":
        cmds.setAttr(jointObj_str+".lockInfluenceWeights",1)
    else:
        cmds.error("hogehoge")

unlocks = cmds.listRelatives("local_C0_0_jnt",ad=True,typ="joint")
for unlock in unlocks:
    try:
        cmds.setAttr(unlock+".lockInfluenceWeights",0)
    except:
        pass
        
for root in head["root"]:
    for params in root["params"]:
        for transformValue in params["transformValue"]:
            cmds.select(params["vertex"],r=True)
            cmds.skinPercent(root["skc"],tv=[(transformValue["joint"],transformValue["value"])])
            cmds.select(cl=True)
            lockInfluenceSwitch_check_func(params["lockInfluence"])
            #print(root["skc"],params["vertex"],transValue["joint"],transValue["value"])