import maya.cmds as cmds
import json

def get_nCloth(nClothShape,filePass):
    isDynamic = cmds.getAttr(nClothShape + ".isDynamic")
    collide = cmds.getAttr(nClothShape + ".collide")
    selfCollide = cmds.getAttr(nClothShape + ".selfCollide")
    collisionFlag = cmds.getAttr(nClothShape + ".collisionFlag")
    selfCollisionFlag = cmds.getAttr(nClothShape + ".selfCollisionFlag")
    collideStrength = cmds.getAttr(nClothShape + ".collideStrength")
    collisionLayer = cmds.getAttr(nClothShape + ".collisionLayer")
    thickness = cmds.getAttr(nClothShape + ".thickness")
    selfCollideWidthScale = cmds.getAttr(nClothShape + ".selfCollideWidthScale")
    solverDisplay = cmds.getAttr(nClothShape + ".solverDisplay")
    displayColor = cmds.getAttr(nClothShape + ".displayColor")
    displayColorR = cmds.getAttr(nClothShape + ".displayColorR")
    displayColorG = cmds.getAttr(nClothShape + ".displayColorG")
    displayColorB = cmds.getAttr(nClothShape + ".displayColorB")
    bounce = cmds.getAttr(nClothShape + ".bounce")
    friction = cmds.getAttr(nClothShape + ".friction")
    stickiness = cmds.getAttr(nClothShape + ".stickiness")
    collideStrengthMapType = cmds.getAttr(nClothShape + ".collideStrengthMapType")
    collideStrengthMap = cmds.getAttr(nClothShape + ".collideStrengthMap")
    collideStrengthPerVertex = cmds.getAttr(nClothShape + ".collideStrengthPerVertex")
    thicknessMapType = cmds.getAttr(nClothShape + ".thicknessMapType")
    thicknessMap = cmds.getAttr(nClothShape + ".thicknessMap")
    thicknessPerVertex = cmds.getAttr(nClothShape + ".thicknessPerVertex")
    bounceMapType = cmds.getAttr(nClothShape + ".bounceMapType")
    bounceMap = cmds.getAttr(nClothShape + ".bounceMap")
    bouncePerVertex = cmds.getAttr(nClothShape + ".bouncePerVertex")
    frictionMapType = cmds.getAttr(nClothShape + ".frictionMapType")
    frictionMap = cmds.getAttr(nClothShape + ".frictionMap")
    frictionPerVertex = cmds.getAttr(nClothShape + ".frictionPerVertex")
    stickinessMapType = cmds.getAttr(nClothShape + ".stickinessMapType")
    stickinessMap = cmds.getAttr(nClothShape + ".stickinessMap")
    stickinessPerVertex = cmds.getAttr(nClothShape + ".stickinessPerVertex")
    stretchResistance = cmds.getAttr(nClothShape + ".stretchResistance")
    compressionResistance = cmds.getAttr(nClothShape + ".compressionResistance")
    bendResistance = cmds.getAttr(nClothShape + ".bendResistance")
    bendAngleDropoff = cmds.getAttr(nClothShape + ".bendAngleDropoff")
    shearResistance = cmds.getAttr(nClothShape + ".shearResistance")
    restitutionAngle = cmds.getAttr(nClothShape + ".restitutionAngle")
    restitutionTension = cmds.getAttr(nClothShape + ".restitutionTension")
    rigidity = cmds.getAttr(nClothShape + ".rigidity")
    deformResistance = cmds.getAttr(nClothShape + ".deformResistance")
    usePolygonShells = cmds.getAttr(nClothShape + ".usePolygonShells")
    inputMeshAttract = cmds.getAttr(nClothShape + ".inputMeshAttract")
    inputAttractMethod = cmds.getAttr(nClothShape + ".inputAttractMethod")
    inputAttractDamp = cmds.getAttr(nClothShape + ".inputAttractDamp")
    inputMotionDrag = cmds.getAttr(nClothShape + ".inputMotionDrag")
    restLengthScale = cmds.getAttr(nClothShape + ".restLengthScale")
    bendAngleScale = cmds.getAttr(nClothShape + ".bendAngleScale")
    mass = cmds.getAttr(nClothShape + ".pointMass")
    lift = cmds.getAttr(nClothShape + ".lift")
    drag = cmds.getAttr(nClothShape + ".drag")
    tangentialDrag = cmds.getAttr(nClothShape + ".tangentialDrag")
    damp = cmds.getAttr(nClothShape + ".damp")
    stretchDamp = cmds.getAttr(nClothShape + ".stretchDamp")
    scalingRelation = cmds.getAttr(nClothShape + ".scalingRelation")
    ignoreSolverGravity = cmds.getAttr(nClothShape + ".ignoreSolverGravity")
    ignoreSolverWind = cmds.getAttr(nClothShape + ".ignoreSolverWind")
    localForce = cmds.getAttr(nClothShape + ".localForce")
    localForceX = cmds.getAttr(nClothShape + ".localForceX")
    localForceY = cmds.getAttr(nClothShape + ".localForceY")
    localForceZ = cmds.getAttr(nClothShape + ".localForceZ")
    localWind = cmds.getAttr(nClothShape + ".localWind")
    localWindX = cmds.getAttr(nClothShape + ".localWindX")
    localWindY = cmds.getAttr(nClothShape + ".localWindY")
    localWindZ = cmds.getAttr(nClothShape + ".localWindZ")
    stretchMapType = cmds.getAttr(nClothShape + ".stretchMapType")
    stretchMap = cmds.getAttr(nClothShape + ".stretchMap")
    stretchPerVertex = cmds.getAttr(nClothShape + ".stretchPerVertex")
    compressionMapType = cmds.getAttr(nClothShape + ".compressionMapType")
    compressionMap = cmds.getAttr(nClothShape + ".compressionMap")
    compressionPerVertex = cmds.getAttr(nClothShape + ".compressionPerVertex")
    bendMapType = cmds.getAttr(nClothShape + ".bendMapType")
    bendMap = cmds.getAttr(nClothShape + ".bendMap")
    bendPerVertex = cmds.getAttr(nClothShape + ".bendPerVertex")
    bendAngleDropoffMapType = cmds.getAttr(nClothShape + ".bendAngleDropoffMapType")
    bendAngleDropoffMap = cmds.getAttr(nClothShape + ".bendAngleDropoffMap")
    bendAngleDropoffPerVertex = cmds.getAttr(nClothShape + ".bendAngleDropoffPerVertex")
    restitutionAngleMapType = cmds.getAttr(nClothShape + ".restitutionAngleMapType")
    restitutionAngleMap = cmds.getAttr(nClothShape + ".restitutionAngleMap")
    restitutionAnglePerVertex = cmds.getAttr(nClothShape + ".restitutionAnglePerVertex")
    rigidityMapType = cmds.getAttr(nClothShape + ".rigidityMapType")
    rigidityMap = cmds.getAttr(nClothShape + ".rigidityMap")
    rigidityPerVertex = cmds.getAttr(nClothShape + ".rigidityPerVertex")
    deformMapType = cmds.getAttr(nClothShape + ".deformMapType")
    deformMap = cmds.getAttr(nClothShape + ".deformMap")
    deformPerVertex = cmds.getAttr(nClothShape + ".deformPerVertex")
    inputAttractMapType = cmds.getAttr(nClothShape + ".inputAttractMapType")
    inputAttractMap = cmds.getAttr(nClothShape + ".inputAttractMap")
    inputAttractPerVertex = cmds.getAttr(nClothShape + ".inputAttractPerVertex")
    restLengthScaleMapType = cmds.getAttr(nClothShape + ".restLengthScaleMapType")
    restLengthScaleMap = cmds.getAttr(nClothShape + ".restLengthScaleMap")
    restLengthScalePerVertex = cmds.getAttr(nClothShape + ".restLengthScalePerVertex")
    dampMapType = cmds.getAttr(nClothShape + ".dampMapType")
    dampMap = cmds.getAttr(nClothShape + ".dampMap")
    dampPerVertex = cmds.getAttr(nClothShape + ".dampPerVertex")
    massMapType = cmds.getAttr(nClothShape + ".massMapType")
    massMap = cmds.getAttr(nClothShape + ".massMap")
    massPerVertex = cmds.getAttr(nClothShape + ".massPerVertex")
    liftMapType = cmds.getAttr(nClothShape + ".liftMapType")
    liftMap = cmds.getAttr(nClothShape + ".liftMap")
    liftPerVertex = cmds.getAttr(nClothShape + ".liftPerVertex")
    dragMapType = cmds.getAttr(nClothShape + ".dragMapType")
    dragMap = cmds.getAttr(nClothShape + ".dragMap")
    dragPerVertex = cmds.getAttr(nClothShape + ".dragPerVertex")
    tangentialDragMapType = cmds.getAttr(nClothShape + ".tangentialDragMapType")
    tangentialDragMap = cmds.getAttr(nClothShape + ".tangentialDragMap")
    tangentialDragPerVertex = cmds.getAttr(nClothShape + ".tangentialDragPerVertex")
    wrinkleMapType = cmds.getAttr(nClothShape + ".wrinkleMapType")
    wrinkleMap = cmds.getAttr(nClothShape + ".wrinkleMap")
    wrinklePerVertex = cmds.getAttr(nClothShape + ".wrinklePerVertex")
    wrinkleMapScale = cmds.getAttr(nClothShape + ".wrinkleMapScale")
    forceField = cmds.getAttr(nClothShape + ".forceField")
    fieldMagnitude = cmds.getAttr(nClothShape + ".fieldMagnitude")
    fieldDistance = cmds.getAttr(nClothShape + ".fieldDistance")
    fieldScale = cmds.getAttr(nClothShape + ".fieldScale")
    fieldScale_Position = cmds.getAttr(nClothShape + ".fieldScale.fieldScale_Position")
    fieldScale_FloatValue = cmds.getAttr(nClothShape + ".fieldScale.fieldScale_FloatValue")
    fieldScale_Interp = cmds.getAttr(nClothShape + ".fieldScale.fieldScale_Interp")
    fieldMagnitudeMapType = cmds.getAttr(nClothShape + ".fieldMagnitudeMapType")
    fieldMagnitudeMap = cmds.getAttr(nClothShape + ".fieldMagnitudeMap")
    fieldMagnitudePerVertex = cmds.getAttr(nClothShape + ".fieldMagnitudePerVertex")
    airPushDistance = cmds.getAttr(nClothShape + ".airPushDistance")
    airPushVorticity = cmds.getAttr(nClothShape + ".airPushVorticity")
    windShadowDistance = cmds.getAttr(nClothShape + ".windShadowDistance")
    windShadowDiffusion = cmds.getAttr(nClothShape + ".windShadowDiffusion")
    windSelfShadow = cmds.getAttr(nClothShape + ".windSelfShadow")
    pressureMethod = cmds.getAttr(nClothShape + ".pressureMethod")
    pressure = cmds.getAttr(nClothShape + ".pressure")
    pressureDamping = cmds.getAttr(nClothShape + ".pressureDamping")
    startPressure = cmds.getAttr(nClothShape + ".startPressure")
    pumpRate = cmds.getAttr(nClothShape + ".pumpRate")
    airTightness = cmds.getAttr(nClothShape + ".airTightness")
    incompressibility = cmds.getAttr(nClothShape + ".incompressibility")
    sealHoles = cmds.getAttr(nClothShape + ".sealHoles")
    maxIterations = cmds.getAttr(nClothShape + ".maxIterations")
    maxSelfCollisionIterations = cmds.getAttr(nClothShape + ".maxSelfCollisionIterations")
    collideLastThreshold = cmds.getAttr(nClothShape + ".collideLastThreshold")
    addCrossLinks = cmds.getAttr(nClothShape + ".addCrossLinks")
    evaluationOrder = cmds.getAttr(nClothShape + ".evaluationOrder")
    bendSolver = cmds.getAttr(nClothShape + ".bendSolver")
    sortLinks = cmds.getAttr(nClothShape + ".sortLinks")
    trappedCheck = cmds.getAttr(nClothShape + ".trappedCheck")
    selfTrappedCheck = cmds.getAttr(nClothShape + ".selfTrappedCheck")
    pushOut = cmds.getAttr(nClothShape + ".pushOut")
    pushOutRadius = cmds.getAttr(nClothShape + ".pushOutRadius")
    crossoverPush = cmds.getAttr(nClothShape + ".crossoverPush")
    selfCrossoverPush = cmds.getAttr(nClothShape + ".selfCrossoverPush")
    cacheableAttributes = cmds.getAttr(nClothShape + ".cacheableAttributes")
    cacheUsage = cmds.getAttr(nClothShape + ".cacheUsage")
    startFrame = cmds.getAttr(nClothShape + ".startFrame")
    currentTime = cmds.getAttr(nClothShape + ".currentTime")
    s = {nClothShape:[isDynamic,collide,selfCollide,collisionFlag,selfCollisionFlag,collideStrength,collisionLayer,thickness,selfCollideWidthScale,solverDisplay,displayColor,displayColorR,displayColorG,displayColorB,bounce,friction,stickiness,collideStrengthMapType,collideStrengthMap,collideStrengthPerVertex,thicknessMapType,thicknessMap,thicknessPerVertex,bounceMapType,bounceMap,bouncePerVertex,frictionMapType,frictionMap,frictionPerVertex,stickinessMapType,stickinessMap,stickinessPerVertex,stretchResistance,compressionResistance,bendResistance,bendAngleDropoff,shearResistance,restitutionAngle,restitutionTension,rigidity,deformResistance,usePolygonShells,inputMeshAttract,inputAttractMethod,inputAttractDamp,inputMotionDrag,restLengthScale,bendAngleScale,mass,lift,drag,tangentialDrag,damp,stretchDamp,scalingRelation,ignoreSolverGravity,ignoreSolverWind,localForce,localForceX,localForceY,localForceZ,localWind,localWindX,localWindY,localWindZ,stretchMapType,stretchMap,stretchPerVertex,compressionMapType,compressionMap,compressionPerVertex,bendMapType,bendMap,bendPerVertex,bendAngleDropoffMapType,bendAngleDropoffMap,bendAngleDropoffPerVertex,restitutionAngleMapType,restitutionAngleMap,restitutionAnglePerVertex,rigidityMapType,rigidityMap,rigidityPerVertex,deformMapType,deformMap,deformPerVertex,inputAttractMapType,inputAttractMap,inputAttractPerVertex,restLengthScaleMapType,restLengthScaleMap,restLengthScalePerVertex,dampMapType,dampMap,dampPerVertex,massMapType,massMap,massPerVertex,liftMapType,liftMap,liftPerVertex,dragMapType,dragMap,dragPerVertex,tangentialDragMapType,tangentialDragMap,tangentialDragPerVertex,wrinkleMapType,wrinkleMap,wrinklePerVertex,wrinkleMapScale,forceField,fieldMagnitude,fieldDistance,fieldScale,fieldScale_Position,fieldScale_FloatValue,fieldScale_Interp,fieldMagnitudeMapType,fieldMagnitudeMap,fieldMagnitudePerVertex,airPushDistance,airPushVorticity,windShadowDistance,windShadowDiffusion,windSelfShadow,pressureMethod,pressure,pressureDamping,startPressure,pumpRate,airTightness,incompressibility,sealHoles,maxIterations,maxSelfCollisionIterations,collideLastThreshold,addCrossLinks,evaluationOrder,bendSolver,sortLinks,trappedCheck,selfTrappedCheck,pushOut,pushOutRadius,crossoverPush,selfCrossoverPush,cacheableAttributes,cacheUsage,startFrame,currentTime]}
    with open(filePass, "w") as f:
        json.dump(s, f, indent = 4, ensure_ascii =False)

def set_nCloth(nClothShape,filePass):
    with open(filePass, 'r') as f:
        nClothDict = json.load(f)
        nClothParams = nClothDict[nClothShape]
    cmds.setAttr(nClothShape + ".overrideEnabled", nClothParams[0])
    cmds.setAttr(nClothShape + ".collide", nClothParams[1])
    cmds.setAttr(nClothShape + ".selfCollide", nClothParams[2])
    cmds.setAttr(nClothShape + ".collisionFlag", nClothParams[3])
    cmds.setAttr(nClothShape + ".selfCollisionFlag", nClothParams[4])
    cmds.setAttr(nClothShape + ".collideStrength", nClothParams[5])
    cmds.setAttr(nClothShape + ".collisionLayer", nClothParams[6])
    cmds.setAttr(nClothShape + ".thickness", nClothParams[7])
    cmds.setAttr(nClothShape + ".selfCollideWidthScale", nClothParams[8])
    cmds.setAttr(nClothShape + ".solverDisplay", nClothParams[9])
    cmds.setAttr(nClothShape + ".displayColor", nClothParams[10])
    cmds.setAttr(nClothShape + ".displayColorR", nClothParams[11])
    cmds.setAttr(nClothShape + ".displayColorG", nClothParams[12])
    cmds.setAttr(nClothShape + ".displayColorB", nClothParams[13])
    cmds.setAttr(nClothShape + ".bounce", nClothParams[14])
    cmds.setAttr(nClothShape + ".friction", nClothParams[15])
    cmds.setAttr(nClothShape + ".stickiness", nClothParams[16])
    cmds.setAttr(nClothShape + ".collideStrengthMapType", nClothParams[17])
    cmds.setAttr(nClothShape + ".collideStrengthMap", nClothParams[18])
    cmds.setAttr(nClothShape + ".collideStrengthPerVertex", nClothParams[19])
    cmds.setAttr(nClothShape + ".thicknessMapType", nClothParams[20])
    cmds.setAttr(nClothShape + ".thicknessMap", nClothParams[21])
    cmds.setAttr(nClothShape + ".thicknessPerVertex", nClothParams[22])
    cmds.setAttr(nClothShape + ".bounceMapType", nClothParams[23])
    cmds.setAttr(nClothShape + ".bounceMap", nClothParams[24])
    cmds.setAttr(nClothShape + ".bouncePerVertex", nClothParams[25])
    cmds.setAttr(nClothShape + ".frictionMapType", nClothParams[26])
    cmds.setAttr(nClothShape + ".frictionMap", nClothParams[27])
    cmds.setAttr(nClothShape + ".frictionPerVertex", nClothParams[28])
    cmds.setAttr(nClothShape + ".stickinessMapType", nClothParams[29])
    cmds.setAttr(nClothShape + ".stickinessMap", nClothParams[30])
    cmds.setAttr(nClothShape + ".stickinessPerVertex", nClothParams[31])
    cmds.setAttr(nClothShape + ".stretchResistance", nClothParams[32])
    cmds.setAttr(nClothShape + ".compressionResistance", nClothParams[33])
    cmds.setAttr(nClothShape + ".bendResistance", nClothParams[34])
    cmds.setAttr(nClothShape + ".bendAngleDropoff", nClothParams[35])
    cmds.setAttr(nClothShape + ".shearResistance", nClothParams[36])
    cmds.setAttr(nClothShape + ".restitutionAngle", nClothParams[37])
    cmds.setAttr(nClothShape + ".restitutionTension", nClothParams[38])
    cmds.setAttr(nClothShape + ".rigidity", nClothParams[39])
    cmds.setAttr(nClothShape + ".deformResistance", nClothParams[40])
    cmds.setAttr(nClothShape + ".usePolygonShells", nClothParams[41])
    cmds.setAttr(nClothShape + ".inputMeshAttract", nClothParams[42])
    cmds.setAttr(nClothShape + ".inputAttractMethod", nClothParams[43])
    cmds.setAttr(nClothShape + ".inputAttractDamp", nClothParams[44])
    cmds.setAttr(nClothShape + ".inputMotionDrag", nClothParams[45])
    cmds.setAttr(nClothShape + ".restLengthScale", nClothParams[46])
    cmds.setAttr(nClothShape + ".bendAngleScale", nClothParams[47])
    cmds.setAttr(nClothShape + ".mass", nClothParams[48])
    cmds.setAttr(nClothShape + ".lift", nClothParams[49])
    cmds.setAttr(nClothShape + ".drag", nClothParams[50])
    cmds.setAttr(nClothShape + ".tangentialDrag", nClothParams[51])
    cmds.setAttr(nClothShape + ".damp", nClothParams[52])
    cmds.setAttr(nClothShape + ".stretchDamp", nClothParams[53])
    cmds.setAttr(nClothShape + ".scalingRelation", nClothParams[54])
    cmds.setAttr(nClothShape + ".ignoreSolverGravity", nClothParams[55])
    cmds.setAttr(nClothShape + ".ignoreSolverWind", nClothParams[56])
    cmds.setAttr(nClothShape + ".localForce", nClothParams[57])
    cmds.setAttr(nClothShape + ".localForceX", nClothParams[58])
    cmds.setAttr(nClothShape + ".localForceY", nClothParams[59])
    cmds.setAttr(nClothShape + ".localForceZ", nClothParams[60])
    cmds.setAttr(nClothShape + ".localWind", nClothParams[61])
    cmds.setAttr(nClothShape + ".localWindX", nClothParams[62])
    cmds.setAttr(nClothShape + ".localWindY", nClothParams[63])
    cmds.setAttr(nClothShape + ".localWindZ", nClothParams[64])
    cmds.setAttr(nClothShape + ".stretchMapType", nClothParams[65])
    cmds.setAttr(nClothShape + ".stretchMap", nClothParams[66])
    cmds.setAttr(nClothShape + ".stretchPerVertex", nClothParams[67])
    cmds.setAttr(nClothShape + ".compressionMapType", nClothParams[68])
    cmds.setAttr(nClothShape + ".compressionMap", nClothParams[69])
    cmds.setAttr(nClothShape + ".compressionPerVertex", nClothParams[70])
    cmds.setAttr(nClothShape + ".bendMapType", nClothParams[71])
    cmds.setAttr(nClothShape + ".bendMap", nClothParams[72])
    cmds.setAttr(nClothShape + ".bendPerVertex", nClothParams[73])
    cmds.setAttr(nClothShape + ".bendAngleDropoffMapType", nClothParams[74])
    cmds.setAttr(nClothShape + ".bendAngleDropoffMap", nClothParams[75])
    cmds.setAttr(nClothShape + ".bendAngleDropoffPerVertex", nClothParams[76])
    cmds.setAttr(nClothShape + ".restitutionAngleMapType", nClothParams[77])
    cmds.setAttr(nClothShape + ".restitutionAngleMap", nClothParams[78])
    cmds.setAttr(nClothShape + ".restitutionAnglePerVertex", nClothParams[79])
    cmds.setAttr(nClothShape + ".rigidityMapType", nClothParams[80])
    cmds.setAttr(nClothShape + ".rigidityMap", nClothParams[81])
    cmds.setAttr(nClothShape + ".rigidityPerVertex", nClothParams[82])
    cmds.setAttr(nClothShape + ".deformMapType", nClothParams[83])
    cmds.setAttr(nClothShape + ".deformMap", nClothParams[84])
    cmds.setAttr(nClothShape + ".deformPerVertex", nClothParams[85])
    cmds.setAttr(nClothShape + ".inputAttractMapType", nClothParams[86])
    cmds.setAttr(nClothShape + ".inputAttractMap", nClothParams[87])
    cmds.setAttr(nClothShape + ".inputAttractPerVertex", nClothParams[88])
    cmds.setAttr(nClothShape + ".restLengthScaleMapType", nClothParams[89])
    cmds.setAttr(nClothShape + ".restLengthScaleMap", nClothParams[90])
    cmds.setAttr(nClothShape + ".restLengthScalePerVertex", nClothParams[91])
    cmds.setAttr(nClothShape + ".dampMapType", nClothParams[92])
    cmds.setAttr(nClothShape + ".dampMap", nClothParams[93])
    cmds.setAttr(nClothShape + ".dampPerVertex", nClothParams[94])
    cmds.setAttr(nClothShape + ".massMapType", nClothParams[95])
    cmds.setAttr(nClothShape + ".massMap", nClothParams[96])
    cmds.setAttr(nClothShape + ".massPerVertex", nClothParams[97])
    cmds.setAttr(nClothShape + ".liftMapType", nClothParams[98])
    cmds.setAttr(nClothShape + ".liftMap", nClothParams[99])
    cmds.setAttr(nClothShape + ".liftPerVertex", nClothParams[100])
    cmds.setAttr(nClothShape + ".dragMapType", nClothParams[101])
    cmds.setAttr(nClothShape + ".dragMap", nClothParams[102])
    cmds.setAttr(nClothShape + ".dragPerVertex", nClothParams[103])
    cmds.setAttr(nClothShape + ".tangentialDragMapType", nClothParams[104])
    cmds.setAttr(nClothShape + ".tangentialDragMap", nClothParams[105])
    cmds.setAttr(nClothShape + ".tangentialDragPerVertex", nClothParams[106])
    cmds.setAttr(nClothShape + ".wrinkleMapType", nClothParams[107])
    cmds.setAttr(nClothShape + ".wrinkleMap", nClothParams[108])
    cmds.setAttr(nClothShape + ".wrinklePerVertex", nClothParams[109])
    cmds.setAttr(nClothShape + ".wrinkleMapScale", nClothParams[110])
    cmds.setAttr(nClothShape + ".forceField", nClothParams[111])
    cmds.setAttr(nClothShape + ".fieldMagnitude", nClothParams[112])
    cmds.setAttr(nClothShape + ".fieldDistance", nClothParams[113])
    cmds.setAttr(nClothShape + ".fieldScale", nClothParams[114])
    cmds.setAttr(nClothShape + ".fieldScale.fieldScale_Position", nClothParams[115])
    cmds.setAttr(nClothShape + ".fieldScale.fieldScale_FloatValue", nClothParams[116])
    cmds.setAttr(nClothShape + ".fieldScale.fieldScale_Interp", nClothParams[117])
    cmds.setAttr(nClothShape + ".fieldMagnitudeMapType", nClothParams[118])
    cmds.setAttr(nClothShape + ".fieldMagnitudeMap", nClothParams[119])
    cmds.setAttr(nClothShape + ".fieldMagnitudePerVertex", nClothParams[120])
    cmds.setAttr(nClothShape + ".airPushDistance", nClothParams[121])
    cmds.setAttr(nClothShape + ".airPushVorticity", nClothParams[122])
    cmds.setAttr(nClothShape + ".windShadowDistance", nClothParams[123])
    cmds.setAttr(nClothShape + ".windShadowDiffusion", nClothParams[124])
    cmds.setAttr(nClothShape + ".windSelfShadow", nClothParams[125])
    cmds.setAttr(nClothShape + ".pressureMethod", nClothParams[126])
    cmds.setAttr(nClothShape + ".pressure", nClothParams[127])
    cmds.setAttr(nClothShape + ".pressureDamping", nClothParams[128])
    cmds.setAttr(nClothShape + ".startPressure", nClothParams[129])
    cmds.setAttr(nClothShape + ".pumpRate", nClothParams[130])
    cmds.setAttr(nClothShape + ".airTightness", nClothParams[131])
    cmds.setAttr(nClothShape + ".incompressibility", nClothParams[132])
    cmds.setAttr(nClothShape + ".sealHoles", nClothParams[133])
    cmds.setAttr(nClothShape + ".maxIterations", nClothParams[134])
    cmds.setAttr(nClothShape + ".maxSelfCollisionIterations", nClothParams[135])
    cmds.setAttr(nClothShape + ".collideLastThreshold", nClothParams[136])
    cmds.setAttr(nClothShape + ".addCrossLinks", nClothParams[137])
    cmds.setAttr(nClothShape + ".evaluationOrder", nClothParams[138])
    cmds.setAttr(nClothShape + ".bendSolver", nClothParams[139])
    cmds.setAttr(nClothShape + ".sortLinks", nClothParams[140])
    cmds.setAttr(nClothShape + ".trappedCheck", nClothParams[141])
    cmds.setAttr(nClothShape + ".selfTrappedCheck", nClothParams[142])
    cmds.setAttr(nClothShape + ".pushOut", nClothParams[143])
    cmds.setAttr(nClothShape + ".pushOutRadius", nClothParams[144])
    cmds.setAttr(nClothShape + ".crossoverPush", nClothParams[145])
    cmds.setAttr(nClothShape + ".selfCrossoverPush", nClothParams[146])
    cmds.setAttr(nClothShape + ".cacheableAttributes", nClothParams[147])
    cmds.setAttr(nClothShape + ".cacheUsage", nClothParams[148])
    cmds.setAttr(nClothShape + ".startFrame", nClothParams[149])
    cmds.setAttr(nClothShape + ".currentTime", nClothParams[150])

def get_nucleus(nucleus,filePass):
    enable = cmds.getAttr(nucleus + ".enable")
    visibility = cmds.getAttr(nucleus + ".visibility")
    gravity = cmds.getAttr(nucleus + ".gravity")
    gravityDirectionX = cmds.getAttr(nucleus + ".gravityDirectionX")
    gravityDirectionY = cmds.getAttr(nucleus + ".gravityDirectionY")
    gravityDirectionZ = cmds.getAttr(nucleus + ".gravityDirectionZ")
    subSteps = cmds.getAttr(nucleus + ".subSteps")
    maxCollisionIterations = cmds.getAttr(nucleus + ".maxCollisionIterations")
    collisionLayerRange = cmds.getAttr(nucleus + ".collisionLayerRange")
    startFrame = cmds.getAttr(nucleus + ".startFrame")
    frameJumpLimit = cmds.getAttr(nucleus + ".frameJumpLimit")
    timeScale = cmds.getAttr(nucleus + ".timeScale")
    spaceScale = cmds.getAttr(nucleus + ".spaceScale")

    s = {nucleus:[enable,visibility,gravity,gravityDirectionX,gravityDirectionY,gravityDirectionZ,subSteps,maxCollisionIterations,collisionLayerRange,startFrame,frameJumpLimit,timeScale,spaceScale]}
    with open(filePass, "w") as f:
        json.dump(s, f, indent = 4, ensure_ascii =False)

def set_nucleus(nucleus, filePass):
    with open(filePass, 'r') as f:
        nucleusDict = json.load(f)
        nucleusParams = nucleusDict[nucleus]
    cmds.setAttr(nucleus + ".enable", nucleusParams[0])
    cmds.setAttr(nucleus + ".visibility", nucleusParams[1])
    cmds.setAttr(nucleus + ".gravity", nucleusParams[2])
    cmds.setAttr(nucleus + ".gravityDirectionX", nucleusParams[3])
    cmds.setAttr(nucleus + ".gravityDirectionY", nucleusParams[4])
    cmds.setAttr(nucleus + ".gravityDirectionZ", nucleusParams[5])
    cmds.setAttr(nucleus + ".subSteps", nucleusParams[6])
    cmds.setAttr(nucleus + ".maxCollisionIterations", nucleusParams[7])
    cmds.setAttr(nucleus + ".collisionLayerRange", nucleusParams[8])
    cmds.setAttr(nucleus + ".startFrame", nucleusParams[9])
    cmds.setAttr(nucleus + ".frameJumpLimit", nucleusParams[10])
    cmds.setAttr(nucleus + ".timeScale", nucleusParams[11])
    cmds.setAttr(nucleus + ".spaceScale", nucleusParams[12])

def nucleusRun():
    nucleus = "joe_nucleus"
    filePass =  "nucleus.json"
    #get_nucleus(nucleus,filePass)
    set_nucleus(nucleus,filePass)

def shirtRun():
    nClothShape = "C_shirt_cthShape"
    filePass =  "nCloth_shirt.json"
    
    get_nCloth(nClothShape,filePass)
    #set_nCloth(nClothShape,filePass)

def trouserRun():
    nClothShape = "C_shirt_cthShape"
    filePass =  "nCloth_trouser.json"
    
    get_nCloth(nClothShape,filePass)
    #set_nCloth(nClothShape,filePass)

def main():
    #nucleusRun()
    shirtRun()
    #trouserRun()

main()

nClothShape = "C_shirt_cthShape"
attr_list = cmds.listAttr(nClothShape, k = True)